export const translations = {
  fr: {
    "lang.fr": "FR", "lang.en": "EN",
    /* === NAV === */
    "nav.home": "🏠 Accueil",
    "nav.apropos": "👤 À propos",
    "nav.alternance": "🏢 Alternance",
    "nav.alt-arrivee": "• Arrivée",
    "nav.alt-equipe": "• Équipe infra",
    "nav.alt-tuteur": "• Tuteur",
    "nav.alt-transdev": "• Transdev",
    "nav.projets": "🛠️ Projets",
    "nav.certifications": "🏅 Certifications",
    "nav.cert-reseau": "• Réseau",
    "nav.cert-systemes": "• Systèmes",
    "nav.cert-cloud": "• Cloud",
    "nav.cert-securite": "• Sécurité",
    "nav.cert-devops": "• DevOps / IaC",
    "nav.cert-itsm": "• ITSM / Gouvernance",
    "nav.cert-outils": "• Outils / Supervision",
    "nav.cert-autres": "• Autres",
    "nav.veille": "🔒 Veille technologique",
    "nav.cyberveille": "🛡️ Cyberveille",
    "nav.blogs": "📝 Blogs",
    "nav.contact": "📞 Contact",
    "nav.jeu": "🎮 Jeu – Dino SIO",
    /* === HOME === */
    "home.title": "[=== BIENVENUE ===]",
    "home.welcome": "Bienvenue sur le portfolio de <strong>Londé Balossa Lotus Espoir</strong>.",
    "home.instructions": "Utilise le menu en haut pour naviguer.",
    /* === APROPOS === */
    "apropos.title": "[=== À PROPOS ===]",
    "apropos.intro": "Étudiant en BTS SIO (option SISR), je m'intéresse aux systèmes, réseaux et à la cybersécurité. Mon objectif : bâtir des infrastructures <strong>performantes</strong>, <strong>sécurisées</strong> et <strong>résilientes</strong>.",
    "apropos.infra.title": "Enjeux des infrastructures réseau aujourd'hui",
    "apropos.infra.1": "<strong>Performance &amp; scalabilité</strong> – absorber la croissance utilisateurs/données/services.",
    "apropos.infra.2": "<strong>Sécurité</strong> – faire face aux ransomwares, compromissions d'identités, exposition Internet.",
    "apropos.infra.3": "<strong>Disponibilité</strong> – maintenir un service 24/7 avec redondance, sauvegardes, PRA/PCA.",
    "apropos.future.title": "Dans la prochaine décennie",
    "apropos.future.1": "<strong>Automatisation &amp; IaC/SDN</strong> – réseaux pilotés par code, déploiements répétables.",
    "apropos.future.2": "<strong>Zero Trust généralisé</strong> – contrôle d'accès fort, moindre privilège, vérification continue.",
    "apropos.future.3": "<strong>Observabilité</strong> – télémétrie fine, détection temps réel, auto-remédiation.",
    "apropos.future.4": "<strong>IA &amp; sécurité</strong> – détection d'anomalies, réponse automatisée.",
    "apropos.assistant": "Assistant IA accessible depuis le bouton flottant en bas à droite.",
    /* === ALTERNANCE === */
    "alternance.title": "[=== MON ALTERNANCE CHEZ TRANSDEV ===]",
    "alternance.subtabs.label": "Sous-onglets Alternance",
    "alt-arrivee.title": "Arrivée au sein du groupe Transdev",
    "alt-arrivee.text": "(À compléter : contexte d'arrivée, objectifs de la mission, périmètre technique…)",
    "alt-equipe.title": "L'équipe infrastructure",
    "alt-equipe.text": "(À compléter : organisation, responsabilités, technologies principales, interactions…)",
    "alt-tuteur.title": "Présentation",
    "alt-tuteur.p1": "<strong>Johann Launay</strong> est <strong>Asset Manager</strong> / gestionnaire du parc informatique à la <strong>DSI France</strong> de Transdev. Dans un entretien publié par Transdev, il met en avant les actions de sobriété énergétique et l'optimisation du cycle de vie des équipements (reconditionnement, réduction des emballages, méthodes de réception et logistique à Roissy) dans une démarche de gestion responsable des actifs IT. <a href=\"https://www.transdev.com/fr/innovation-et-tech/la-dsi-france-et-la-sobriete-energetique-entretien-avec-johann-launay-gestionnaire-du-parc-informatique/\" target=\"_blank\" rel=\"noopener\">Source</a>.",
    "alt-tuteur.role.title": "Rôle &amp; missions (extraits publics)",
    "alt-tuteur.role.1": "<strong>Gestion du parc IT &amp; sobriété :</strong> pilotage du cycle de vie des équipements, reconditionnement, logistique (plateforme de Roissy), réduction des impacts environnementaux liés aux actifs informatiques (démarche décrite par Transdev). <a href=\"https://www.transdev.com/fr/innovation-et-tech/la-dsi-france-et-la-sobriete-energetique-entretien-avec-johann-launay-gestionnaire-du-parc-informatique/\" target=\"_blank\" rel=\"noopener\">Source</a>.",
    "alt-tuteur.role.2": "<strong>Parcours IT (éléments antérieurs, profil pro) :</strong> responsabilités systèmes, réseaux, data center, projets de consolidation d'infrastructures et d'outillage IT (ex. GLPI, supervision), telles que décrites sur un profil professionnel public (Viadeo/JDN). <a href=\"https://viadeo.journaldunet.com/p/johann-launay-5047557\" target=\"_blank\" rel=\"noopener\">Source</a>.",
    "alt-tuteur.note1": "(Les items ci‑dessus reflètent uniquement des informations <em>publiques</em> et professionnelles.)",
    "alt-tuteur.role-internal.title": "Fonctionnement avec mon tuteur (éléments internes)",
    "alt-tuteur.role-internal.1": "<strong>Rituel hebdo :</strong> point <strong>30&nbsp;min chaque début de semaine</strong> pour cadrer priorités, risques et livrables.",
    "alt-tuteur.role-internal.2": "<strong>Montée en autonomie :</strong> démonstration → binômage → réalisation encadrée → validation.",
    "alt-tuteur.role-internal.3": "<strong>Traçabilité :</strong> ticketing + documentation des SOP/Runbooks + preuves pour E6.",
    "alt-tuteur.note2": "Ces informations décrivent notre organisation interne (non publiques).",
    "alt-tuteur.learned.title": "Ce que j'apprends à ses côtés",
    "alt-tuteur.learned.1": "<strong>Démarrage en IT d'entreprise :</strong> j'ai véritablement fait mes débuts en environnement pro avec lui ; il a posé les bases (méthode, qualité, sécurité).",
    "alt-tuteur.learned.2": "<strong>Gestion d'actifs IT \"responsable\" :</strong> penser cycle de vie complet (inventaire → exploitation → retrait), standardiser et mesurer l'impact (KPI simples).",
    "alt-tuteur.learned.3": "<strong>Exigence &amp; mentorat :</strong> Johann est une vraie source de motivation et un <strong>mentor</strong> — il challenge, explique, et valide les étapes clés.",
    "alt-transdev.title": "Qui est Transdev&nbsp;?",
    "alt-transdev.p1": "Transdev est un opérateur et intégrateur de mobilités présent dans <strong>19&nbsp;pays</strong>, qui transporte en moyenne <strong>12,8&nbsp;millions</strong> de passagers par jour et emploie plus de <strong>105&nbsp;000</strong> collaborateurs (2024). Modes exploités&nbsp;: bus, car, tram, train, métro, ferries, vélo, transport à la demande et services autonomes. <a href=\"https://fr.linkedin.com/company/-transdev\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.gouv.title": "Actionnariat &amp; gouvernance",
    "alt-transdev.gouv.1": "<strong>Actionnariat (2025) :</strong> Groupe <strong>RETHMANN 66&nbsp;%</strong> et <strong>Caisse des Dépôts 34&nbsp;%</strong> – finalisation annoncée le 2&nbsp;juillet&nbsp;2025. <a href=\"https://www.transdev.com/wp-content/uploads/2025/07/2025-07-02-presse-release-rethmann-caisse-des-depots-transdev_en.pdf\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.gouv.2": "<strong>Gouvernance :</strong> comité exécutif groupe (PDG Thierry Mallet, etc.) détaillé sur la page officielle. <a href=\"https://www.transdev.com/fr/notre-groupe/qui-dirige-le-groupe/\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.chiffres.title": "Chiffres 2024 (repères officiels)",
    "alt-transdev.chiffres.1": "<strong>CA 2024 :</strong> ~<strong>10,05&nbsp;Md€</strong> (cap franchi) ; <strong>12,8&nbsp;M</strong> de passagers/jour en moyenne.",
    "alt-transdev.chiffres.2": "<strong>Performance :</strong> résultat opérationnel courant 2024 en forte hausse (<em>donnée institutionnelle</em>).",
    "alt-transdev.chiffres.3": "<strong>Emploi :</strong> +<strong>105&nbsp;000</strong> collaborateurs, recrutements importants en 2024.",
    "alt-transdev.chiffres.note": "Sources institutionnelles (Caisse des Dépôts / pages corporate). <a href=\"https://www.caissedesdepots.fr/eclairage/actualites/transdev-sest-surpasse-en-2024\" target=\"_blank\" rel=\"noopener\">CDC 13&nbsp;mars&nbsp;2025</a> · <a href=\"https://fr.linkedin.com/company/-transdev\" target=\"_blank\" rel=\"noopener\">Transdev (présentation)</a>",
    "alt-transdev.strat.title": "Stratégie numérique &amp; gestion d'actifs (EAM)",
    "alt-transdev.strat.1": "<strong>Standardisation EAM cloud :</strong> déploiements Infor CloudSuite EAM (Australasie) pour centraliser achats, maintenance, inventaires &amp; conformité. <a href=\"https://www.technologydecisions.com.au/content/cloud-and-virtualisation/news/transdev-selects-infor-for-cloud-based-asset-management-270053092\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.strat.2": "<strong>Cadres ISO&nbsp;55001 :</strong> approches multi‑modalités et corpus de pratiques (AMBoK) pour aligner performance, sécurité et contrats. <a href=\"https://amcouncil.win/2023/08/11/transdev-multi-modal-asset-management-strategy-establishing-asset-management-body-of-knowledge-ambok/\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.strat.3": "<strong>Cas d'usage :</strong> prise en main rapide d'un réseau ferroviaire en Suède en 2024 via outillage d'asset management (référence presse). <a href=\"https://railwaynews.net/transdev-sweden-rapid-rail-network-takeover-asset-management-success.html\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.sober.title": "IT &amp; sobriété (exemple France)",
    "alt-transdev.sober.1": "En France, la DSI met en avant la <strong>sobriété énergétique</strong> et une gestion responsable du parc IT : reconditionnement des matériels, réduction des emballages, méthodes de réception &amp; logistique (plateforme de Roissy), pour limiter l'empreinte des équipements. <a href=\"https://www.transdev.com/fr/innovation-et-tech/la-dsi-france-et-la-sobriete-energetique-entretien-avec-johann-launay-gestionnaire-du-parc-informatique/\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.links.title": "Où suivre l'officiel",
    "alt-transdev.links.1": "Gouvernance (ComEx)",
    "alt-transdev.links.2": "Investors &amp; résultats",
    "alt-transdev.links.3": "Présentation (LinkedIn corp.)",
    /* === PROJETS === */
    "projets.title": "[=== PROJETS ===]",
    "projets.tab.crystal": "Refresh Réseau Crystal",
    "projets.tab.zerotrust": "Zero Trust &amp; Supervision Zabbix",
    /* === PROJET ZERO TRUST LAB === */
    "zt-lab.intro.title": "Zero Trust &amp; Supervision Zabbix",
    "zt-lab.intro.p": "Projet personnel de lab réseau visant à mettre en œuvre une architecture <strong>Zero Trust</strong> sur un réseau segmenté en VLANs, supervisé par <strong>Zabbix</strong>. L'objectif est de simuler un environnement professionnel sécurisé : aucun accès implicite, contrôle strict des flux, isolation des équipements legacy, et visibilité complète via monitoring.",
    "zt-lab.intro.ul": "<li><strong>Contexte :</strong> lab personnel, matériel physique réel</li><li><strong>Durée :</strong> projet continu – itérations régulières</li><li><strong>Stack :</strong> ASA 5505, switches managés, Zabbix, VLANs, SNMP</li>",
    "zt-lab.arch.title": "Architecture réseau",
    "zt-lab.arch.p": "Chaque équipement a un rôle précis dans la chaîne de sécurité :",
    "zt-lab.arch.ul": "<li><strong>Routeur (edge) :</strong> point d'entrée WAN, NAT, filtrage initial.</li><li><strong>Firewall ASA 5505 :</strong> cœur Zero Trust — règles ACL strictes, aucun flux autorisé par défaut, inspection des paquets inter-VLAN.</li><li><strong>Switch managé :</strong> segmentation L2 en VLANs, trunk vers le firewall, port-security activé.</li><li><strong>VLANs :</strong> isolation logique complète entre les zones (Users, Admin, Servers, Legacy).</li><li><strong>Zabbix (serveur de supervision) :</strong> collecte SNMP, alertes en temps réel, dashboard centralisé.</li>",
    "zt-lab.schema.title": "Schéma détaillé",
    "zt-lab.schema.p": "Vue complète de l'architecture Zero Trust du lab, incluant les flux autorisés, les zones de confiance et la position de Zabbix.",
    "zt-lab.schema.placeholder": "📐 Schéma à ajouter — placer l'image dans <code>images/zerotrust-schema.png</code>",
    "zt-lab.schema.legend": "Légende : les flèches vertes représentent les flux autorisés par ACL, les rouges les flux bloqués par défaut. Zabbix collecte en lecture seule via SNMP (VLAN 20 → VLAN 30).",
    "zt-lab.vlan.title": "Segmentation VLAN",
    "zt-lab.vlan.p": "Chaque zone est isolée — aucune communication inter-VLAN sans règle ACL explicite sur le firewall.",
    "zt-lab.vlan.th.id": "VLAN", "zt-lab.vlan.th.nom": "Nom", "zt-lab.vlan.th.role": "Rôle", "zt-lab.vlan.th.acces": "Accès inter-VLAN",
    "zt-lab.vlan.r1.nom": "Users",  "zt-lab.vlan.r1.role": "Postes utilisateurs",      "zt-lab.vlan.r1.acces": "Internet uniquement",
    "zt-lab.vlan.r2.nom": "Admin",  "zt-lab.vlan.r2.role": "Zabbix, supervision",      "zt-lab.vlan.r2.acces": "Lecture SNMP vers VLAN 30",
    "zt-lab.vlan.r3.nom": "Servers","zt-lab.vlan.r3.role": "Serveurs internes",         "zt-lab.vlan.r3.acces": "Accès restreint depuis VLAN 10/20",
    "zt-lab.vlan.r4.nom": "Legacy", "zt-lab.vlan.r4.role": "PS3 (équipement isolé)",   "zt-lab.vlan.r4.acces": "Aucun — totalement isolé",
    "zt-lab.secu.title": "Sécurité Zero Trust appliquée",
    "zt-lab.secu.ul": "<li><strong>Aucun accès par défaut :</strong> toutes les ACL commencent par un <code>deny any any</code> — seuls les flux explicitement autorisés passent.</li><li><strong>Filtrage firewall ASA :</strong> inspection stateful, ACL nommées par zone, logging de chaque refus.</li><li><strong>Isolation legacy :</strong> la PS3 (VLAN 40) est totalement coupée des autres zones.</li><li><strong>Contrôle inter-VLAN :</strong> chaque flux entre zones est explicitement défini dans les ACL du firewall.</li><li><strong>Port-security switch :</strong> verrouillage des ports par adresse MAC pour éviter les intrusions physiques.</li>",
    "zt-lab.zabbix.title": "Supervision avec Zabbix",
    "zt-lab.zabbix.p": "Zabbix est déployé sur le VLAN Admin (20). Il supervise l'ensemble de l'infrastructure en lecture seule.",
    "zt-lab.zabbix.ul": "<li><strong>SNMP v2c/v3 :</strong> collecte des métriques sur switch, routeur et ASA (CPU, interfaces, trafic).</li><li><strong>Logs réseau :</strong> syslog centralisé depuis le firewall — chaque refus ACL est tracé.</li><li><strong>Monitoring firewall :</strong> état des interfaces, connexions actives, taux de refus.</li><li><strong>Dashboard :</strong> vue globale de la santé réseau, graphiques de bande passante par VLAN.</li><li><strong>Alertes email/SMS :</strong> déclenchées sur seuil (interface down, trafic anormal, refus massifs).</li>",
    "zt-lab.scenarios.title": "Scénarios de test &amp; alertes",
    "zt-lab.scenarios.ul": "<li><strong>Intrusion PS3 détectée :</strong> tentative de ping depuis VLAN 40 → refus ASA + alerte Zabbix.</li><li><strong>Scan réseau détecté :</strong> nmap depuis VLAN Users → logs syslog + alerte refus ACL élevé.</li><li><strong>Interface ASA down :</strong> alerte critique Zabbix en moins de 60 secondes.</li><li><strong>Connexion admin non autorisée :</strong> tentative SSH vers Servers depuis VLAN Users → refus + log immédiat.</li>",
    "zt-lab.results.title": "Résultats &amp; compétences validées",
    "zt-lab.results.ul": "<li><strong>Surface d'attaque réduite :</strong> aucun équipement joignable sans règle explicite.</li><li><strong>Visibilité réseau complète :</strong> chaque flux, refus et anomalie est visible dans Zabbix.</li><li><strong>Architecture reproductible :</strong> configuration documentée, exportable vers un environnement de production.</li><li><strong>Compétences E6 :</strong> conception infrastructure, sécurité réseau, supervision, documentation technique.</li>",
    "crystal.intro.title": "Refresh Réseau Crystal ▸ WAN / LAN / WLAN / SD‑WAN v2",
    "crystal.intro.p": "Projet majeur de modernisation réseau du siège Crystal : migration des firewalls vers une architecture SD‑WAN v2, remplacement complet du LAN et du WLAN, montée en débit WAN et déploiement progressif en environnement de production réel.",
    "crystal.tab.overview": "Vue globale",
    "crystal.tab.architecture": "Architecture",
    "crystal.tab.planning": "Planning",
    "crystal.tab.risques": "Risques",
    "crystal.tab.suivi": "Suivi migration",
    "crystal.tab.role": "Rôle &amp; E6",
    "crystal.overview.h3": "Vue globale du projet",
    "crystal.overview.ul": "<li>Modernisation complète du réseau du siège Crystal</li><li>Infrastructure critique avec utilisateurs en production</li><li>Approche progressive et sécurisée</li><li>Objectif : performance, sécurité et résilience</li>",
    "crystal.overview.context.h3": "Contexte",
    "crystal.overview.context.p": "Le siège Crystal disposait d'une infrastructure vieillissante nécessitant une modernisation complète pour améliorer la performance, la sécurité et la résilience.",
    "crystal.overview.objectives.h3": "Objectifs",
    "crystal.overview.objectives.ul": "<li>Migration Firewalls vers Fortigate 200G (SDWANv2)</li><li>Montée en débit WAN (2G / 8G / 10G)</li><li>Remplacement de 53 switches</li><li>Déploiement de 80 bornes WiFi</li><li>POC 1er étage avant déploiement global</li><li>Processus complet ITIL : Change, CAB, rollback</li>",
    "crystal.arch.h3": "Architecture &amp; aspects techniques",
    "crystal.arch.schemas.h3": "Schémas techniques – SD‑WAN V2 Crystal",
    "crystal.arch.schemas.p": "(Images à venir)",
    "crystal.arch.simple.h3": "Architecture (vue simplifiée)",
    "crystal.planning.h3": "Planning &amp; organisation",
    "crystal.planning.ul": "<li>Semaine du 13 avril : préparation préproduction</li><li>24 avril : tests et communication utilisateurs</li><li>25–26 avril : migration firewalls</li><li>27–28 avril : VSR (suivi renforcé)</li><li>16 mai : POC LAN / Wi‑Fi</li><li>Mai → juillet : déploiement global par étage</li>",
    "crystal.planning.phases.h3": "Planning (extrait par phases)",
    "crystal.planning.phases.ul": "<li>Phase 1 : Préparation &amp; Design</li><li>Phase 2 : Configuration &amp; Validation</li><li>Phase 3 : Migration Firewalls</li><li>Phase 4 : POC LAN/WLAN</li><li>Phase 5 : Déploiement global</li>",
    "crystal.risques.h3": "Analyse des risques",
    "crystal.risques.ul": "<li>Contraintes physiques en baie (espace, câblage)</li><li>Brassage LAN/WLAN complexe</li><li>Dépendance aux ressources terrain</li><li>Liaisons opérateurs non disponibles au démarrage</li>",
    "crystal.risques.p": "Des décisions de migration progressive et de rollback ont été prises pour sécuriser la mise en production.",
    "crystal.risques.fiche.h3": "Migration réseau — fiche synthèse",
    "crystal.risques.fiche.context.h4": "Contexte",
    "crystal.risques.fiche.context.p": "Migration et renouvellement d'équipements (switches, firewall, SD‑WAN).<br>Objectif : migration 1→1 et préparation upgrade 8‑Core.<br>Réunion : plan staging, export config, recâblage.",
    "crystal.risques.fiche.problemes.h4": "Problèmes rencontrés",
    "crystal.risques.fiche.problemes.ul": "<li>Reprise 1→1 obligatoire.</li><li>Impact licences pour 8‑Core.</li><li>Indisponibilité d'acteurs clés.</li>",
    "crystal.risques.fiche.decisions.h4": "Décisions prises",
    "crystal.risques.fiche.decisions.ul": "<li>Préparer config sur la base de l'existant (1→1).</li><li>Recâblage par l'équipe dédiée ; export fourni.</li>",
    "crystal.risques.fiche.actions.h4": "Actions techniques",
    "crystal.risques.fiche.actions.ul": "<li>Export configuration switch.</li><li>Staging en laboratoire et scripts d'import.</li><li>Reprise interfaces/VLAN, vérif. règles firewall.</li>",
    "crystal.risques.fiche.blocages.h4": "Blocages projet",
    "crystal.risques.fiche.blocages.ul": "<li>Validation manager requise (licences/budget).</li><li>Dépendance présence terrain pour repérage.</li>",
    "crystal.risques.fiche.suite.h4": "Suite du projet",
    "crystal.risques.fiche.suite.ul": "<li>Point dédié avec le manager pour valider l'upgrade.</li><li>Planifier repérage, fixer date d'intervention.</li>",
    "crystal.risques.fiche.monrole.h4": "Mon rôle",
    "crystal.risques.fiche.monrole.ul": "<li>Participation aux réunions de coordination.</li><li>Analyse technique et préparation des exports.</li><li>Support staging et tests de reprise.</li>",
    "crystal.suivi.h3": "Refresh Réseau Crystal — Suivi de migration",
    "crystal.suivi.context.h4": "Contexte",
    "crystal.suivi.context.p": "Modernisation du réseau du siège Crystal (SD‑WAN v2).<br>Migration des firewalls en plusieurs phases.<br>Enjeu : continuité de service et sécurité.",
    "crystal.suivi.problemes.h4": "Problèmes rencontrés",
    "crystal.suivi.problemes.ul": "<li>Reports de la migration firewall.</li><li>Manque de ressources et charge de travail élevée.</li><li>Risques d'impact sur d'autres projets.</li>",
    "crystal.suivi.decisions.h4": "Décisions prises",
    "crystal.suivi.decisions.ul": "<li>Replanification avec nouvelle date définie.</li><li>Préparation renforcée avant migration.</li><li>Priorisation de la sécurité et des tests.</li>",
    "crystal.suivi.actions.h4": "Actions techniques",
    "crystal.suivi.actions.ul": "<li>Firewalls installés, rackés et câblés.</li><li>Configuration SD‑WAN v2 en cours.</li><li>Brassage et étiquetage des câbles.</li><li>Tests LAN, WAN, WiFi.</li>",
    "crystal.suivi.risques.h4": "Risques identifiés",
    "crystal.suivi.risques.ul": "<li>Surcharge des outils de supervision.</li><li>Tests applicatifs incomplets.</li><li>Règles firewall manquantes ou incohérentes.</li><li>Dépendances externes (serveurs, vidéo, accès).</li>",
    "crystal.suivi.orga.h4": "Organisation de l'opération",
    "crystal.suivi.orga.ul": "<li>Préparation en amont pour réduire les risques.</li><li>Migration avec tests techniques + fonctionnels.</li><li>Rollback possible en cas de problème.</li><li>Supervision renforcée post‑migration.</li>",
    "crystal.suivi.suite.h4": "Suite du projet",
    "crystal.suivi.suite.ul": "<li>Mise à jour planning.</li><li>Finalisation tests métier.</li><li>Validation règles firewall.</li><li>Préparation support post‑migration.</li>",
    "crystal.suivi.monrole.h4": "Mon rôle",
    "crystal.suivi.monrole.ul": "<li>Participation aux réunions de suivi.</li><li>Compréhension du projet réseau.</li><li>Observation de la coordination équipes.</li>",
    "crystal.suivi.competences.h4": "Compétences développées",
    "crystal.suivi.competences.ul": "<li>Réseaux (LAN, WAN, SD‑WAN).</li><li>Sécurité (firewall, règles de filtrage).</li><li>Gestion de projet et analyse des risques.</li><li>Travail en équipe multi‑domaine.</li>",
    "crystal.role.h3": "Rôle personnel",
    "crystal.role.ul": "<li>Participation aux ateliers techniques</li><li>Analyse réseau existant &amp; logs FW</li><li>Préparation équipements (staging)</li><li>Tests pré/post migration</li><li>Documentation &amp; suivi projet</li>",
    "crystal.role.e6.h3": "Compétences E6 validées",
    "crystal.role.e6.ul": "<li>Conception d'infrastructure</li><li>Installation &amp; configuration</li><li>Tests &amp; validation</li><li>Supervision &amp; exploitation</li><li>Gestion de projet &amp; ITIL</li>",
    /* === CERTIFICATIONS === */
    "certifications.title": "[=== CERTIFICATIONS ===]",
    "cert.h2.objectifs": "Objectifs",
    "cert.h2.parcours": "Parcours &amp; ressources",
    "cert.h2.etat": "État",
    "cert.reseau.obj.ul": "<li>Maîtriser routage, commutation, IPv4/IPv6, VLAN, ACL.</li>",
    "cert.reseau.parcours.ul": "<li>#CCNA — plan de révision (PDF)</li><li>#JNCIA — notes &amp; lab (Lien)</li>",
    "cert.reseau.etat.ul": "<li>CCNA — <em>en préparation</em></li><li>JNCIA — <em>à moyen terme</em></li>",
    "cert.sys.obj.ul": "<li>Linux (services, réseau), Windows (install, gestion, AD de base).</li>",
    "cert.sys.parcours.ul": "<li>#LPIC‑1 — plan (PDF)</li><li>#Windows Admin — checklists</li>",
    "cert.sys.etat.ul": "<li>LPIC‑1 — <em>en préparation</em></li>",
    "cert.cloud.obj.ul": "<li>Fondamentaux Azure/AWS (IAM, compute, réseau, stockage).</li>",
    "cert.cloud.parcours.ul": "<li>#AZ‑900 — mémo (PDF)</li><li>#AWS CCP — notes</li>",
    "cert.cloud.etat.ul": "<li>AZ‑900 — <em>prévu</em></li><li>AWS CCP — <em>prévu</em></li>",
    "cert.secu.obj.ul": "<li>Socle sécurité (concepts, IAM, réseau, endpoint, cloud, conformité).</li>",
    "cert.secu.parcours.ul": "<li>#Security+ — notes</li><li>#NSE 1‑3 — progression</li><li>#SC‑900 — mémo</li>",
    "cert.secu.etat.ul": "<li>NSE 1‑3 — <em>en cours/obtenu (détailler)</em></li><li>Security+ — <em>à moyen terme</em></li>",
    "cert.devops.obj.ul": "<li>Containerisation, orchestration et IaC (Docker, K8s, Terraform).</li>",
    "cert.devops.parcours.ul": "<li>#Docker Associate — mémo</li><li>#Terraform Associate — labs</li>",
    "cert.devops.etat.ul": "<li>Terraform Associate — <em>prévu</em></li>",
    "cert.itsm.obj.ul": "<li>Bonnes pratiques ITSM &amp; cycle de vie des services.</li>",
    "cert.itsm.parcours.ul": "<li>#ITIL® Foundation — mémo</li>",
    "cert.itsm.etat.ul": "<li>ITIL® Foundation — <em>prévu</em></li>",
    "cert.outils.obj.ul": "<li>Mettre en œuvre et superviser (Zabbix, ELK) + exploitation.</li>",
    "cert.outils.parcours.ul": "<li>#Zabbix — parcours</li><li>#ELK — fiches</li>",
    "cert.outils.etat.ul": "<li>Zabbix — <em>en pratique</em></li>",
    "cert.autres.h2": "Autres badges / langues",
    "cert.autres.ul": "<li>TOEIC / Voltaire / Badges internes (à compléter)</li>",
    /* === JEU === */
    "jeu.title": "[=== JEU – DINO SIO ===]",
    "jeu.btn.start": "▶ Démarrer",
    "jeu.btn.restart": "⟲ Rejouer",
    "jeu.btn.difficulty": "⚙ Régler la difficulté",
    "jeu.score.label": "Score",
    "jeu.level.label": "Niveau",
    "jeu.modal.title": "Difficulté",
    "jeu.modal.p": "Si ce bouton existait, ce ne serait pas fun 😉",
    "jeu.modal.label": "Niveau",
    "jeu.modal.hint": "(désactivé par choix philosophique)",
    "jeu.modal.close": "Fermer",
    "jeu.note": "Astuce : presse <kbd>Espace</kbd> ou <kbd>↑</kbd> pour sauter. Sur mobile, touche le canvas.",
    /* === VEILLE === */
    "veille.title": "[=== VEILLE TECHNOLOGIQUE ===]",
    "veille.theme": "Thème : <strong>Zero Trust Security Model</strong> (<em>Zero Trust Architecture</em>).",
    "veille.tab.concepts": "Concepts",
    "veille.tab.architecture": "Architecture",
    "veille.tab.usecases": "Cas d'usage",
    "veille.tab.analysis": "Analyse personnelle",
    "zt.concepts.h2": "Qu'est‑ce que le Zero Trust ?",
    "zt.concepts.p": "Le <strong>Zero Trust Security Model</strong> repose sur un principe fondamental : <strong>ne jamais faire confiance par défaut</strong>. Chaque accès est vérifié en continu, même à l'intérieur du réseau.",
    "zt.principles.h2": "Principes fondamentaux",
    "zt.principles.ul": "<li><strong>Vérification systématique</strong> — authentification de chaque requête.</li><li><strong>Moindre privilège</strong> — accès strictement nécessaire.</li><li><strong>Micro‑segmentation</strong> — isolation des ressources.</li><li><strong>Contrôle continu</strong> — évaluation permanente du contexte.</li><li><strong>Supposition de compromission</strong> — l'attaque peut venir de partout.</li>",
    "zt.compare.h2": "Avant / Après Zero Trust",
    "zt.compare.th1": "Modèle traditionnel",
    "zt.compare.th2": "Modèle Zero Trust",
    "zt.compare.r1c1": "Confiance implicite", "zt.compare.r1c2": "Confiance vérifiée",
    "zt.compare.r2c1": "Périmètre réseau",   "zt.compare.r2c2": "Identité &amp; contexte",
    "zt.compare.r3c1": "Accès large",          "zt.compare.r3c2": "Accès minimal",
    "zt.compare.r4c1": "Détection tardive",    "zt.compare.r4c2": "Surveillance continue",
    "zt.arch.simple.h2": "Schéma Zero Trust (vue simplifiée)",
    "zt.arch.advanced.h2": "Schéma Zero Trust (avancé)",
    "zt.usecase.google.h2": "Étude de cas : Google BeyondCorp",
    "zt.usecase.google.p": "Google a supprimé la notion de réseau interne de confiance. Chaque accès passe par une vérification d'identité et de contexte.",
    "zt.usecase.enterprise.h2": "Cas d'usage en entreprise",
    "zt.usecase.enterprise.ul": "<li>Remplacement du VPN par <strong>ZTNA</strong></li><li>Segmentation des serveurs</li><li>MFA obligatoire</li><li>Contrôle de conformité des postes</li><li>Analyse comportementale en temps réel</li>",
    "zt.usecase.ransomware.h2": "Exemple : attaque ransomware",
    "zt.usecase.ransomware.p1": "<strong>Sans Zero Trust :</strong> propagation rapide.",
    "zt.usecase.ransomware.p2": "<strong>Avec Zero Trust :</strong>",
    "zt.usecase.ransomware.ul": "<li>MFA bloque l'accès initial</li><li>Micro‑segmentation limite la propagation</li><li>EDR/XDR détecte l'anomalie</li><li>Accès compromis automatiquement coupé</li>",
    "zt.analysis.h2": "Analyse personnelle",
    "zt.analysis.p1": "Le Zero Trust représente pour moi une évolution logique de la cybersécurité moderne dans des environnements distribués.",
    "zt.analysis.p2": "Il combine IAM, MFA, supervision et architecture réseau, ce qui correspond à ma manière de travailler et à mon projet professionnel.",
    "zt.conclusion.h2": "Conclusion",
    "zt.conclusion.p": "Le Zero Trust n'est pas un produit mais une stratégie globale indispensable pour renforcer la résilience face aux menaces actuelles.",
    "zt.faq.h2": "FAQ Zero Trust",
    "zt.faq.ul": "<li><strong>Zéro confiance ?</strong> → confiance vérifiée.</li><li><strong>Remplace le VPN ?</strong> → oui, via ZTNA.</li><li><strong>Déploiement long ?</strong> → progressif.</li><li><strong>Réservé aux grandes entreprises ?</strong> → non.</li>",
    /* === CYBERVEILLE === */
    "cyberveille.title": "[=== AGRÉGATEUR CYBERSÉCURITÉ ===]",
    "cyberveille.sub": "Sources faisant autorité, dédupliquées et triées automatiquement — archives conservées 7 jours.",
    "cyberveille.history.title": "Historique (7 jours)",
    "cyberveille.sources.title": "Sources",
    "cyberveille.criticalOnly": "🚨 Alertes critiques / CVE uniquement",
    "cyberveille.recent.title": "Consultés récemment",
    "cyberveille.recent.empty": "Aucun article consulté pour l'instant.",
    "cyberveille.loading": "📡 Chargement des actualités…",
    /* === CONTACT === */
    "contact.title": "[=== CONTACT ===]",
    "contact.nom": "Nom : <strong>Londé Balossa Lotus Espoir</strong>",
    "contact.email": "Email : <a href=\"mailto:londe305@gmail.com\">londe305@gmail.com</a>",
    "contact.linkedin": "LinkedIn : <a href=\"https://www.linkedin.com/feed/\" target=\"_blank\" rel=\"noopener\">Mon Profil LinkedIn</a>",
  },

  en: {
    "lang.fr": "FR", "lang.en": "EN",
    /* === NAV === */
    "nav.home": "🏠 Home",
    "nav.apropos": "👤 About",
    "nav.alternance": "🏢 Internship",
    "nav.alt-arrivee": "• Arrival",
    "nav.alt-equipe": "• Infra Team",
    "nav.alt-tuteur": "• Tutor",
    "nav.alt-transdev": "• Transdev",
    "nav.projets": "🛠️ Projects",
    "nav.certifications": "🏅 Certifications",
    "nav.cert-reseau": "• Network",
    "nav.cert-systemes": "• Systems",
    "nav.cert-cloud": "• Cloud",
    "nav.cert-securite": "• Security",
    "nav.cert-devops": "• DevOps / IaC",
    "nav.cert-itsm": "• ITSM / Governance",
    "nav.cert-outils": "• Tools / Monitoring",
    "nav.cert-autres": "• Other",
    "nav.veille": "🔒 Tech Watch",
    "nav.cyberveille": "🛡️ Cyber Watch",
    "nav.blogs": "📝 Blogs",
    "nav.contact": "📞 Contact",
    "nav.jeu": "🎮 Game – Dino SIO",
    /* === HOME === */
    "home.title": "[=== WELCOME ===]",
    "home.welcome": "Welcome to the portfolio of <strong>Londé Balossa Lotus Espoir</strong>.",
    "home.instructions": "Use the top navigation menu to explore the portfolio.",
    /* === APROPOS === */
    "apropos.title": "[=== ABOUT ===]",
    "apropos.intro": "BTS SIO student (SISR option), I focus on systems, networks and cybersecurity. My goal: build <strong>performant</strong>, <strong>secure</strong> and <strong>resilient</strong> infrastructures.",
    "apropos.infra.title": "Network infrastructure challenges today",
    "apropos.infra.1": "<strong>Performance &amp; scalability</strong> – absorb user/data/service growth.",
    "apropos.infra.2": "<strong>Security</strong> – face ransomware, identity compromise, Internet exposure.",
    "apropos.infra.3": "<strong>Availability</strong> – keep service 24/7 with redundancy, backups, DR/BC plans.",
    "apropos.future.title": "In the next decade",
    "apropos.future.1": "<strong>Automation &amp; IaC/SDN</strong> – code-driven networks, repeatable deployments.",
    "apropos.future.2": "<strong>Wider Zero Trust</strong> – strong access control, least privilege, continuous verification.",
    "apropos.future.3": "<strong>Observability</strong> – detailed telemetry, real-time detection, self-remediation.",
    "apropos.future.4": "<strong>AI &amp; security</strong> – anomaly detection, automated response.",
    "apropos.assistant": "AI assistant available from the floating button in the bottom right.",
    /* === ALTERNANCE === */
    "alternance.title": "[=== MY INTERNSHIP AT TRANSDEV ===]",
    "alternance.subtabs.label": "Internship subtabs",
    "alt-arrivee.title": "Arrival at Transdev",
    "alt-arrivee.text": "(To complete: arrival context, mission objectives, technical scope…)",
    "alt-equipe.title": "Infrastructure team",
    "alt-equipe.text": "(To complete: organization, responsibilities, main technologies, interactions…)",
    "alt-tuteur.title": "Presentation",
    "alt-tuteur.p1": "<strong>Johann Launay</strong> is an <strong>Asset Manager</strong> / IT asset manager at Transdev France IT. In an interview, he highlights energy sobriety actions and lifecycle optimization of equipment (refurbishment, reduced packaging, reception and logistics in Roissy) in a responsible IT asset management approach. <a href=\"https://www.transdev.com/fr/innovation-et-tech/la-dsi-france-et-la-sobriete-energetique-entretien-avec-johann-launay-gestionnaire-du-parc-informatique/\" target=\"_blank\" rel=\"noopener\">Source</a>.",
    "alt-tuteur.role.title": "Role &amp; missions (public excerpts)",
    "alt-tuteur.role.1": "<strong>IT asset management &amp; sobriety:</strong> lifecycle management of equipment, refurbishment, logistics (Roissy platform), reducing environmental impacts of IT assets (as described by Transdev). <a href=\"https://www.transdev.com/fr/innovation-et-tech/la-dsi-france-et-la-sobriete-energetique-entretien-avec-johann-launay-gestionnaire-du-parc-informatique/\" target=\"_blank\" rel=\"noopener\">Source</a>.",
    "alt-tuteur.role.2": "<strong>IT career (prior experience):</strong> system, network, data center responsibilities, infrastructure consolidation and IT tooling projects (e.g. GLPI, monitoring), as described on a public professional profile. <a href=\"https://viadeo.journaldunet.com/p/johann-launay-5047557\" target=\"_blank\" rel=\"noopener\">Source</a>.",
    "alt-tuteur.note1": "(The above items reflect only public and professional information.)",
    "alt-tuteur.role-internal.title": "Working with my tutor (internal notes)",
    "alt-tuteur.role-internal.1": "<strong>Weekly ritual:</strong> 30-minute meeting at the start of each week to align priorities, risks and deliverables.",
    "alt-tuteur.role-internal.2": "<strong>Growing autonomy:</strong> demonstration → paired work → supervised execution → validation.",
    "alt-tuteur.role-internal.3": "<strong>Traceability:</strong> ticketing + SOP/Runbook documentation + evidence for E6.",
    "alt-tuteur.note2": "These details describe our internal organization (not public).",
    "alt-tuteur.learned.title": "What I learn alongside him",
    "alt-tuteur.learned.1": "<strong>Starting in enterprise IT:</strong> I truly began my professional experience with him; he set the foundations (method, quality, security).",
    "alt-tuteur.learned.2": "<strong>Responsible IT asset management:</strong> thinking about the full lifecycle (inventory → operation → retirement), standardizing and measuring impact (simple KPIs).",
    "alt-tuteur.learned.3": "<strong>Demanding mentorship:</strong> Johann is a real source of motivation and a <strong>mentor</strong> — he challenges, explains, and validates key steps.",
    "alt-transdev.title": "Who is Transdev?",
    "alt-transdev.p1": "Transdev is a mobility operator and integrator present in <strong>19 countries</strong>, transporting an average of <strong>12.8 million</strong> passengers per day and employing more than <strong>105,000</strong> people (2024). Modes: bus, coach, tram, train, metro, ferries, bike, on-demand and autonomous services. <a href=\"https://fr.linkedin.com/company/-transdev\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.gouv.title": "Ownership &amp; governance",
    "alt-transdev.gouv.1": "<strong>Ownership (2025):</strong> RETHMANN Group 66% and Caisse des Dépôts 34% – completion announced July 2, 2025. <a href=\"https://www.transdev.com/wp-content/uploads/2025/07/2025-07-02-presse-release-rethmann-caisse-des-depots-transdev_en.pdf\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.gouv.2": "<strong>Governance:</strong> group executive committee (CEO Thierry Mallet, etc.) detailed on the official page. <a href=\"https://www.transdev.com/fr/notre-groupe/qui-dirige-le-groupe/\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.chiffres.title": "2024 Figures (official references)",
    "alt-transdev.chiffres.1": "<strong>2024 Revenue:</strong> ~<strong>€10.05B</strong> (milestone reached); <strong>12.8M</strong> passengers/day average.",
    "alt-transdev.chiffres.2": "<strong>Performance:</strong> strong increase in current operating income in 2024 (<em>institutional data</em>).",
    "alt-transdev.chiffres.3": "<strong>Workforce:</strong> +<strong>105,000</strong> employees, significant hiring in 2024.",
    "alt-transdev.chiffres.note": "Institutional sources (Caisse des Dépôts / corporate pages). <a href=\"https://www.caissedesdepots.fr/eclairage/actualites/transdev-sest-surpasse-en-2024\" target=\"_blank\" rel=\"noopener\">CDC March 13, 2025</a> · <a href=\"https://fr.linkedin.com/company/-transdev\" target=\"_blank\" rel=\"noopener\">Transdev (presentation)</a>",
    "alt-transdev.strat.title": "Digital strategy &amp; asset management (EAM)",
    "alt-transdev.strat.1": "<strong>Cloud EAM standardization:</strong> Infor CloudSuite EAM deployments (Australasia) to centralize purchasing, maintenance, inventories &amp; compliance. <a href=\"https://www.technologydecisions.com.au/content/cloud-and-virtualisation/news/transdev-selects-infor-for-cloud-based-asset-management-270053092\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.strat.2": "<strong>ISO 55001 frameworks:</strong> multimodal approaches and practice corpus (AMBoK) to align performance, security and contracts. <a href=\"https://amcouncil.win/2023/08/11/transdev-multi-modal-asset-management-strategy-establishing-asset-management-body-of-knowledge-ambok/\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.strat.3": "<strong>Use case:</strong> quick takeover of a Swedish rail network in 2024 using asset management tooling (press reference). <a href=\"https://railwaynews.net/transdev-sweden-rapid-rail-network-takeover-asset-management-success.html\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.sober.title": "IT &amp; sustainability (France example)",
    "alt-transdev.sober.1": "In France, the IT department promotes <strong>energy sobriety</strong> and responsible IT asset management: equipment refurbishment, reduced packaging, reception &amp; logistics methods (Roissy platform), to limit equipment footprint. <a href=\"https://www.transdev.com/fr/innovation-et-tech/la-dsi-france-et-la-sobriete-energetique-entretien-avec-johann-launay-gestionnaire-du-parc-informatique/\" target=\"_blank\" rel=\"noopener\">Source</a>",
    "alt-transdev.links.title": "Where to follow the official sources",
    "alt-transdev.links.1": "Governance (ComEx)",
    "alt-transdev.links.2": "Investors &amp; results",
    "alt-transdev.links.3": "Presentation (LinkedIn corp.)",
    /* === PROJETS === */
    "projets.title": "[=== PROJECTS ===]",
    "projets.tab.crystal": "Crystal Network Refresh",
    "projets.tab.zerotrust": "Zero Trust &amp; Zabbix Monitoring",
    /* === PROJET ZERO TRUST LAB === */
    "zt-lab.intro.title": "Zero Trust &amp; Zabbix Monitoring",
    "zt-lab.intro.p": "Personal network lab project implementing a <strong>Zero Trust</strong> architecture on a VLAN-segmented network monitored by <strong>Zabbix</strong>. Goal: simulate a professional secure environment — no implicit access, strict traffic control, legacy device isolation, and full visibility via monitoring.",
    "zt-lab.intro.ul": "<li><strong>Context:</strong> personal lab, real physical hardware</li><li><strong>Duration:</strong> ongoing project – regular iterations</li><li><strong>Stack:</strong> ASA 5505, managed switches, Zabbix, VLANs, SNMP</li>",
    "zt-lab.arch.title": "Network architecture",
    "zt-lab.arch.p": "Each device plays a specific role in the security chain:",
    "zt-lab.arch.ul": "<li><strong>Edge router:</strong> WAN entry point, NAT, initial filtering.</li><li><strong>Firewall ASA 5505:</strong> Zero Trust core — strict ACL rules, no flow allowed by default, inter-VLAN packet inspection.</li><li><strong>Managed switch:</strong> L2 segmentation into VLANs, trunk to firewall, port-security enabled.</li><li><strong>VLANs:</strong> full logical isolation between zones (Users, Admin, Servers, Legacy).</li><li><strong>Zabbix (monitoring server):</strong> SNMP collection, real-time alerts, centralized dashboard.</li>",
    "zt-lab.schema.title": "Detailed diagram",
    "zt-lab.schema.p": "Full view of the lab Zero Trust architecture, including authorized flows, trust zones and Zabbix placement.",
    "zt-lab.schema.placeholder": "📐 Diagram to add — place image at <code>images/zerotrust-schema.png</code>",
    "zt-lab.schema.legend": "Legend: green arrows represent ACL-authorized flows, red arrows represent flows blocked by default. Zabbix collects read-only via SNMP (VLAN 20 → VLAN 30).",
    "zt-lab.vlan.title": "VLAN segmentation",
    "zt-lab.vlan.p": "Each zone is isolated — no inter-VLAN communication without an explicit ACL rule on the firewall.",
    "zt-lab.vlan.th.id": "VLAN", "zt-lab.vlan.th.nom": "Name", "zt-lab.vlan.th.role": "Role", "zt-lab.vlan.th.acces": "Inter-VLAN access",
    "zt-lab.vlan.r1.nom": "Users",  "zt-lab.vlan.r1.role": "User workstations",      "zt-lab.vlan.r1.acces": "Internet only",
    "zt-lab.vlan.r2.nom": "Admin",  "zt-lab.vlan.r2.role": "Zabbix, monitoring",     "zt-lab.vlan.r2.acces": "Read-only SNMP to VLAN 30",
    "zt-lab.vlan.r3.nom": "Servers","zt-lab.vlan.r3.role": "Internal servers",        "zt-lab.vlan.r3.acces": "Restricted access from VLAN 10/20",
    "zt-lab.vlan.r4.nom": "Legacy", "zt-lab.vlan.r4.role": "PS3 (isolated device)",  "zt-lab.vlan.r4.acces": "None — fully isolated",
    "zt-lab.secu.title": "Applied Zero Trust security",
    "zt-lab.secu.ul": "<li><strong>No default access:</strong> all ACLs start with <code>deny any any</code> — only explicitly authorized flows pass.</li><li><strong>ASA firewall filtering:</strong> stateful inspection, named ACLs per zone, logging of every denial.</li><li><strong>Legacy isolation:</strong> the PS3 (VLAN 40) is fully cut off from all other zones.</li><li><strong>Inter-VLAN control:</strong> every flow between zones is explicitly defined in firewall ACLs.</li><li><strong>Switch port-security:</strong> MAC address port locking to prevent physical intrusions.</li>",
    "zt-lab.zabbix.title": "Monitoring with Zabbix",
    "zt-lab.zabbix.p": "Zabbix is deployed on the Admin VLAN (20). It monitors the full infrastructure in read-only mode.",
    "zt-lab.zabbix.ul": "<li><strong>SNMP v2c/v3:</strong> metrics collection on switch, router and ASA (CPU, interfaces, traffic).</li><li><strong>Network logs:</strong> centralized syslog from the firewall — every ACL denial is recorded.</li><li><strong>Firewall monitoring:</strong> interface state, active connections, denial rate.</li><li><strong>Dashboard:</strong> global network health view, per-VLAN bandwidth graphs.</li><li><strong>Email/SMS alerts:</strong> triggered on thresholds (interface down, abnormal traffic, mass denials).</li>",
    "zt-lab.scenarios.title": "Test scenarios &amp; alerts",
    "zt-lab.scenarios.ul": "<li><strong>PS3 intrusion detected:</strong> ping attempt from VLAN 40 → ASA denial + Zabbix alert.</li><li><strong>Network scan detected:</strong> nmap from VLAN Users → syslog + high ACL denial alert.</li><li><strong>ASA interface down:</strong> Zabbix critical alert within 60 seconds.</li><li><strong>Unauthorized admin connection:</strong> SSH attempt to Servers from VLAN Users → denial + immediate log.</li>",
    "zt-lab.results.title": "Results &amp; validated skills",
    "zt-lab.results.ul": "<li><strong>Reduced attack surface:</strong> no device reachable without an explicit rule.</li><li><strong>Full network visibility:</strong> every flow, denial and anomaly visible in Zabbix.</li><li><strong>Reproducible architecture:</strong> documented configuration, exportable to a production environment.</li><li><strong>E6 skills:</strong> infrastructure design, network security, monitoring, technical documentation.</li>",
    "crystal.intro.title": "Crystal Network Refresh ▸ WAN / LAN / WLAN / SD‑WAN v2",
    "crystal.intro.p": "Major network modernization project for the Crystal headquarters: firewall migration to SD‑WAN v2 architecture, complete LAN and WLAN replacement, WAN bandwidth upgrade and progressive deployment in a live production environment.",
    "crystal.tab.overview": "Overview",
    "crystal.tab.architecture": "Architecture",
    "crystal.tab.planning": "Planning",
    "crystal.tab.risques": "Risks",
    "crystal.tab.suivi": "Migration tracking",
    "crystal.tab.role": "Role &amp; E6",
    "crystal.overview.h3": "Project overview",
    "crystal.overview.ul": "<li>Complete network modernization of Crystal headquarters</li><li>Critical infrastructure with live production users</li><li>Progressive and secure approach</li><li>Goal: performance, security and resilience</li>",
    "crystal.overview.context.h3": "Context",
    "crystal.overview.context.p": "The Crystal headquarters had an aging infrastructure requiring a complete overhaul to improve performance, security and resilience.",
    "crystal.overview.objectives.h3": "Objectives",
    "crystal.overview.objectives.ul": "<li>Firewall migration to Fortigate 200G (SDWANv2)</li><li>WAN bandwidth upgrade (2G / 8G / 10G)</li><li>Replacement of 53 switches</li><li>Deployment of 80 Wi-Fi access points</li><li>1st floor POC before full deployment</li><li>Full ITIL process: Change, CAB, rollback</li>",
    "crystal.arch.h3": "Architecture &amp; technical aspects",
    "crystal.arch.schemas.h3": "Technical diagrams – SD‑WAN V2 Crystal",
    "crystal.arch.schemas.p": "(Images coming soon)",
    "crystal.arch.simple.h3": "Architecture (simplified view)",
    "crystal.planning.h3": "Planning &amp; organization",
    "crystal.planning.ul": "<li>Week of April 13: pre-production preparation</li><li>April 24: testing and user communication</li><li>April 25–26: firewall migration</li><li>April 27–28: VSR (enhanced monitoring)</li><li>May 16: LAN / Wi-Fi POC</li><li>May → July: floor-by-floor global deployment</li>",
    "crystal.planning.phases.h3": "Planning (phase breakdown)",
    "crystal.planning.phases.ul": "<li>Phase 1: Preparation &amp; Design</li><li>Phase 2: Configuration &amp; Validation</li><li>Phase 3: Firewall Migration</li><li>Phase 4: LAN/WLAN POC</li><li>Phase 5: Full Deployment</li>",
    "crystal.risques.h3": "Risk analysis",
    "crystal.risques.ul": "<li>Physical constraints in rack (space, cabling)</li><li>Complex LAN/WLAN patching</li><li>Dependency on field resources</li><li>Operator links unavailable at start</li>",
    "crystal.risques.p": "Progressive migration and rollback decisions were made to secure the production go-live.",
    "crystal.risques.fiche.h3": "Network migration — summary sheet",
    "crystal.risques.fiche.context.h4": "Context",
    "crystal.risques.fiche.context.p": "Migration and renewal of equipment (switches, firewall, SD-WAN).<br>Goal: 1→1 migration and 8-Core upgrade preparation.<br>Meeting: staging plan, config export, recabling.",
    "crystal.risques.fiche.problemes.h4": "Issues encountered",
    "crystal.risques.fiche.problemes.ul": "<li>Mandatory 1→1 migration.</li><li>License impact for 8-Core.</li><li>Unavailability of key stakeholders.</li>",
    "crystal.risques.fiche.decisions.h4": "Decisions made",
    "crystal.risques.fiche.decisions.ul": "<li>Prepare config based on existing setup (1→1).</li><li>Recabling by dedicated team; export provided.</li>",
    "crystal.risques.fiche.actions.h4": "Technical actions",
    "crystal.risques.fiche.actions.ul": "<li>Switch configuration export.</li><li>Lab staging and import scripts.</li><li>Interface/VLAN takeover, firewall rules verification.</li>",
    "crystal.risques.fiche.blocages.h4": "Project blockers",
    "crystal.risques.fiche.blocages.ul": "<li>Manager validation required (licenses/budget).</li><li>Dependency on on-site presence for survey.</li>",
    "crystal.risques.fiche.suite.h4": "Next steps",
    "crystal.risques.fiche.suite.ul": "<li>Dedicated meeting with manager to validate upgrade.</li><li>Plan survey, set intervention date.</li>",
    "crystal.risques.fiche.monrole.h4": "My role",
    "crystal.risques.fiche.monrole.ul": "<li>Participation in coordination meetings.</li><li>Technical analysis and export preparation.</li><li>Staging support and migration testing.</li>",
    "crystal.suivi.h3": "Crystal Network Refresh — Migration tracking",
    "crystal.suivi.context.h4": "Context",
    "crystal.suivi.context.p": "Crystal headquarters network modernization (SD‑WAN v2).<br>Firewall migration in multiple phases.<br>Stakes: service continuity and security.",
    "crystal.suivi.problemes.h4": "Issues encountered",
    "crystal.suivi.problemes.ul": "<li>Firewall migration postponements.</li><li>Lack of resources and high workload.</li><li>Risk of impact on other projects.</li>",
    "crystal.suivi.decisions.h4": "Decisions made",
    "crystal.suivi.decisions.ul": "<li>Rescheduling with a new date set.</li><li>Enhanced preparation before migration.</li><li>Prioritizing security and testing.</li>",
    "crystal.suivi.actions.h4": "Technical actions",
    "crystal.suivi.actions.ul": "<li>Firewalls installed, racked and cabled.</li><li>SD‑WAN v2 configuration in progress.</li><li>Cable patching and labeling.</li><li>LAN, WAN, WiFi tests.</li>",
    "crystal.suivi.risques.h4": "Identified risks",
    "crystal.suivi.risques.ul": "<li>Monitoring tool overload.</li><li>Incomplete application tests.</li><li>Missing or inconsistent firewall rules.</li><li>External dependencies (servers, video, access).</li>",
    "crystal.suivi.orga.h4": "Operation organization",
    "crystal.suivi.orga.ul": "<li>Upstream preparation to reduce risks.</li><li>Migration with technical + functional tests.</li><li>Rollback possible if issues arise.</li><li>Enhanced monitoring post-migration.</li>",
    "crystal.suivi.suite.h4": "Next steps",
    "crystal.suivi.suite.ul": "<li>Planning update.</li><li>Business test finalization.</li><li>Firewall rules validation.</li><li>Post-migration support preparation.</li>",
    "crystal.suivi.monrole.h4": "My role",
    "crystal.suivi.monrole.ul": "<li>Participation in follow-up meetings.</li><li>Understanding of the network project.</li><li>Observing team coordination.</li>",
    "crystal.suivi.competences.h4": "Skills developed",
    "crystal.suivi.competences.ul": "<li>Networks (LAN, WAN, SD-WAN).</li><li>Security (firewall, filtering rules).</li><li>Project management and risk analysis.</li><li>Multi-domain teamwork.</li>",
    "crystal.role.h3": "Personal role",
    "crystal.role.ul": "<li>Participation in technical workshops</li><li>Existing network analysis &amp; FW logs</li><li>Equipment preparation (staging)</li><li>Pre/post migration tests</li><li>Documentation &amp; project tracking</li>",
    "crystal.role.e6.h3": "Validated E6 skills",
    "crystal.role.e6.ul": "<li>Infrastructure design</li><li>Installation &amp; configuration</li><li>Testing &amp; validation</li><li>Monitoring &amp; operations</li><li>Project management &amp; ITIL</li>",
    /* === CERTIFICATIONS === */
    "certifications.title": "[=== CERTIFICATIONS ===]",
    "cert.h2.objectifs": "Objectives",
    "cert.h2.parcours": "Path &amp; resources",
    "cert.h2.etat": "Status",
    "cert.reseau.obj.ul": "<li>Master routing, switching, IPv4/IPv6, VLAN, ACL.</li>",
    "cert.reseau.parcours.ul": "<li>#CCNA — study plan (PDF)</li><li>#JNCIA — notes &amp; lab (Link)</li>",
    "cert.reseau.etat.ul": "<li>CCNA — <em>in preparation</em></li><li>JNCIA — <em>medium-term</em></li>",
    "cert.sys.obj.ul": "<li>Linux (services, network), Windows (install, management, basic AD).</li>",
    "cert.sys.parcours.ul": "<li>#LPIC‑1 — plan (PDF)</li><li>#Windows Admin — checklists</li>",
    "cert.sys.etat.ul": "<li>LPIC‑1 — <em>in preparation</em></li>",
    "cert.cloud.obj.ul": "<li>Azure/AWS fundamentals (IAM, compute, network, storage).</li>",
    "cert.cloud.parcours.ul": "<li>#AZ‑900 — cheat sheet (PDF)</li><li>#AWS CCP — notes</li>",
    "cert.cloud.etat.ul": "<li>AZ‑900 — <em>planned</em></li><li>AWS CCP — <em>planned</em></li>",
    "cert.secu.obj.ul": "<li>Security foundation (concepts, IAM, network, endpoint, cloud, compliance).</li>",
    "cert.secu.parcours.ul": "<li>#Security+ — notes</li><li>#NSE 1‑3 — progress</li><li>#SC‑900 — cheat sheet</li>",
    "cert.secu.etat.ul": "<li>NSE 1‑3 — <em>in progress/obtained (detail)</em></li><li>Security+ — <em>medium-term</em></li>",
    "cert.devops.obj.ul": "<li>Containerization, orchestration and IaC (Docker, K8s, Terraform).</li>",
    "cert.devops.parcours.ul": "<li>#Docker Associate — cheat sheet</li><li>#Terraform Associate — labs</li>",
    "cert.devops.etat.ul": "<li>Terraform Associate — <em>planned</em></li>",
    "cert.itsm.obj.ul": "<li>ITSM best practices &amp; service lifecycle.</li>",
    "cert.itsm.parcours.ul": "<li>#ITIL® Foundation — cheat sheet</li>",
    "cert.itsm.etat.ul": "<li>ITIL® Foundation — <em>planned</em></li>",
    "cert.outils.obj.ul": "<li>Implement and monitor (Zabbix, ELK) + operations.</li>",
    "cert.outils.parcours.ul": "<li>#Zabbix — learning path</li><li>#ELK — reference sheets</li>",
    "cert.outils.etat.ul": "<li>Zabbix — <em>in practice</em></li>",
    "cert.autres.h2": "Other badges / languages",
    "cert.autres.ul": "<li>TOEIC / Voltaire / Internal badges (to complete)</li>",
    /* === JEU === */
    "jeu.title": "[=== GAME – DINO SIO ===]",
    "jeu.btn.start": "▶ Start",
    "jeu.btn.restart": "⟲ Replay",
    "jeu.btn.difficulty": "⚙ Set difficulty",
    "jeu.score.label": "Score",
    "jeu.level.label": "Level",
    "jeu.modal.title": "Difficulty",
    "jeu.modal.p": "If this button existed, it wouldn't be fun 😉",
    "jeu.modal.label": "Level",
    "jeu.modal.hint": "(disabled by philosophical choice)",
    "jeu.modal.close": "Close",
    "jeu.note": "Tip: press <kbd>Space</kbd> or <kbd>↑</kbd> to jump. On mobile, tap the canvas.",
    /* === VEILLE === */
    "veille.title": "[=== TECH WATCH ===]",
    "veille.theme": "Theme: <strong>Zero Trust Security Model</strong> (<em>Zero Trust Architecture</em>).",
    "veille.tab.concepts": "Concepts",
    "veille.tab.architecture": "Architecture",
    "veille.tab.usecases": "Use cases",
    "veille.tab.analysis": "Personal analysis",
    "zt.concepts.h2": "What is Zero Trust?",
    "zt.concepts.p": "The <strong>Zero Trust Security Model</strong> is based on a fundamental principle: <strong>never trust by default</strong>. Every access is continuously verified, even inside the network.",
    "zt.principles.h2": "Core principles",
    "zt.principles.ul": "<li><strong>Systematic verification</strong> — authentication of every request.</li><li><strong>Least privilege</strong> — strictly necessary access.</li><li><strong>Micro-segmentation</strong> — resource isolation.</li><li><strong>Continuous control</strong> — permanent context evaluation.</li><li><strong>Assume breach</strong> — attacks can come from anywhere.</li>",
    "zt.compare.h2": "Before / After Zero Trust",
    "zt.compare.th1": "Traditional model",
    "zt.compare.th2": "Zero Trust model",
    "zt.compare.r1c1": "Implicit trust",      "zt.compare.r1c2": "Verified trust",
    "zt.compare.r2c1": "Network perimeter",   "zt.compare.r2c2": "Identity &amp; context",
    "zt.compare.r3c1": "Broad access",         "zt.compare.r3c2": "Minimal access",
    "zt.compare.r4c1": "Late detection",       "zt.compare.r4c2": "Continuous monitoring",
    "zt.arch.simple.h2": "Zero Trust diagram (simplified view)",
    "zt.arch.advanced.h2": "Zero Trust diagram (advanced)",
    "zt.usecase.google.h2": "Case study: Google BeyondCorp",
    "zt.usecase.google.p": "Google eliminated the concept of a trusted internal network. Every access goes through identity and context verification.",
    "zt.usecase.enterprise.h2": "Enterprise use cases",
    "zt.usecase.enterprise.ul": "<li>Replacing VPN with <strong>ZTNA</strong></li><li>Server segmentation</li><li>Mandatory MFA</li><li>Device compliance checks</li><li>Real-time behavioral analysis</li>",
    "zt.usecase.ransomware.h2": "Example: ransomware attack",
    "zt.usecase.ransomware.p1": "<strong>Without Zero Trust:</strong> rapid propagation.",
    "zt.usecase.ransomware.p2": "<strong>With Zero Trust:</strong>",
    "zt.usecase.ransomware.ul": "<li>MFA blocks initial access</li><li>Micro-segmentation limits propagation</li><li>EDR/XDR detects the anomaly</li><li>Compromised access automatically cut</li>",
    "zt.analysis.h2": "Personal analysis",
    "zt.analysis.p1": "Zero Trust represents for me a logical evolution of modern cybersecurity in distributed environments.",
    "zt.analysis.p2": "It combines IAM, MFA, monitoring and network architecture, which aligns with my way of working and professional project.",
    "zt.conclusion.h2": "Conclusion",
    "zt.conclusion.p": "Zero Trust is not a product but a comprehensive strategy essential for strengthening resilience against current threats.",
    "zt.faq.h2": "Zero Trust FAQ",
    "zt.faq.ul": "<li><strong>Zero trust?</strong> → verified trust.</li><li><strong>Replaces VPN?</strong> → yes, via ZTNA.</li><li><strong>Long deployment?</strong> → progressive.</li><li><strong>For large enterprises only?</strong> → no.</li>",
    /* === CYBERVEILLE === */
    "cyberveille.title": "[=== CYBERSECURITY AGGREGATOR ===]",
    "cyberveille.sub": "Authoritative sources, deduplicated and automatically sorted — archives kept for 7 days.",
    "cyberveille.history.title": "History (7 days)",
    "cyberveille.sources.title": "Sources",
    "cyberveille.criticalOnly": "🚨 Critical alerts / CVEs only",
    "cyberveille.recent.title": "Recently viewed",
    "cyberveille.recent.empty": "No article viewed yet.",
    "cyberveille.loading": "📡 Loading news…",
    /* === CONTACT === */
    "contact.title": "[=== CONTACT ===]",
    "contact.nom": "Name: <strong>Londé Balossa Lotus Espoir</strong>",
    "contact.email": "Email: <a href=\"mailto:londe305@gmail.com\">londe305@gmail.com</a>",
    "contact.linkedin": "LinkedIn: <a href=\"https://www.linkedin.com/feed/\" target=\"_blank\" rel=\"noopener\">My LinkedIn Profile</a>",
  },
};

export function getStoredLanguage(){
  const lang = localStorage.getItem('portfolioLang');
  if (lang && ['fr','en'].includes(lang)) return lang;
  const browser = navigator.language?.slice(0,2).toLowerCase();
  return ['fr','en'].includes(browser) ? browser : 'fr';
}

export function setLanguage(lang){
  if (!translations[lang]) return;
  document.documentElement.lang = lang;
  localStorage.setItem('portfolioLang', lang);
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    const entry = translations[lang][key];
    if (entry !== undefined) el.textContent = entry;
  });
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.dataset.i18nHtml;
    const entry = translations[lang][key];
    if (entry !== undefined) el.innerHTML = entry;
  });
}

export function initLanguage(){
  const lang = getStoredLanguage();
  setLanguage(lang);
  ['lang-switcher', 'lang-switcher-mob'].forEach(id => {
    document.getElementById(id)?.addEventListener('click', (e) => {
      const btn = e.target.closest('.lang-btn');
      if (!btn) return;
      setLanguage(btn.dataset.lang);
    });
  });
}
